server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location = / {
        try_files /index.html =404;
    }

    location = /cgi-bin/saludo.py {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/saludo.py;
        fastcgi_param SCRIPT_NAME /cgi-bin/saludo.py;
        fastcgi_pass cgi:9000;
    }
}
