# ? Perfil para ejecución JVM tradicional

# Banner visible
spring.main.banner-mode=console

# Logs más detallados
logging.level.root=INFO
logging.level.org.springframework.boot=DEBUG
logging.level.org.springframework.web=DEBUG

# JMX activado
spring.jmx.enabled=true

# DevTools activado si está presente
spring.devtools.restart.enabled=true

# Métricas activadas
management.simple.metrics.export.enabled=true
management.endpoints.web.exposure.include=*

# Puerto estándar
server.port=8080