CREATE TABLE game (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_size  INT       NOT NULL DEFAULT 10,
    status      VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ship (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id       BIGINT    NOT NULL,
    ship_name     VARCHAR(50) NOT NULL,
    length        INT       NOT NULL,
    start_x       INT       NOT NULL,
    start_y       INT       NOT NULL,
    is_horizontal BOOLEAN   NOT NULL,
    sunk          BOOLEAN   NOT NULL DEFAULT FALSE,
    FOREIGN KEY (game_id) REFERENCES game(id) ON DELETE CASCADE
);

CREATE TABLE attack (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id    BIGINT    NOT NULL,
    x          INT       NOT NULL,
    y          INT       NOT NULL,
    hit        BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (game_id) REFERENCES game(id) ON DELETE CASCADE
);
