#+TITLE:
#+AUTHOR:
#+EMAIL:
#+DATE:
#+OPTIONS: texht:t toc:3 num:3 -:nil ^:{} ":nil ':nil
#+OPTIONS: tex:t
#+LATEX_CLASS: article
#+LATEX_HEADER:
#+LANGUAGE: es

#+BEGIN_COMMENT
#+LATEX_HEADER: \usepackage[AUTO]{babel}
#+END_COMMENT

#+LATEX_HEADER_EXTRA: \usepackage{mdframed}
#+LATEX_HEADER_EXTRA: \BeforeBeginEnvironment{minted}{\begin{mdframed}}
#+LATEX_HEADER_EXTRA: \AfterEndEnvironment{minted}{\end{mdframed}}

#+LATEX: \setlength\parindent{10pt}
#+LATEX_HEADER: \usepackage{parskip}

#+latex_header: \usepackage[utf8]{inputenc} %% For unicode chars
#+LATEX_HEADER: \usepackage{placeins}

#+LATEX_HEADER: \usepackage[margin=2.50cm]{geometry}

#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage{mathpazo}
#+LaTeX_HEADER: \linespread{1.05}
#+LaTeX_HEADER: \usepackage[scaled]{helvet}
#+LaTeX_HEADER: \usepackage{courier}

#+LaTeX_HEADER: \hypersetup{colorlinks=true,linkcolor=blue}
#+LATEX_HEADER: \RequirePackage{fancyvrb}
#+LATEX_HEADER: \DefineVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\small,formatcom = {\color[rgb]{0.5,0,0}}}

* More on Data Passing
Passing data through URLs or forms is a fundamental aspect of web
development with PHP. The two primary methods for this are GET and POST,
each with its specific use cases and characteristics.

** GET Method
    :PROPERTIES:
    :CUSTOM_ID: get-method
    :END:

The GET method sends data through the URL. It's primarily used for
requesting data from a specific resource and is visible to the user in
the browser's address bar.

*** Characteristics of GET:
     :PROPERTIES:
     :CUSTOM_ID: characteristics-of-get
     :END:

- Data is appended to the URL as query string parameters.
- Suitable for non-sensitive data, as it's visible in the URL.
- Limited amount of data can be sent (depends on the browser's URL
  length limit).
- Can be bookmarked and cached.
- Faster compared to POST for small amounts of data.

*** Example Usage:
     :PROPERTIES:
     :CUSTOM_ID: example-usage
     :END:

#+begin_src html
  <!-- HTML Form using GET method -->
  <form action="process.php" method="get">
      Name: <input type="text" name="name">
      <input type="submit" value="Submit">
  </form>
#+end_src

In PHP, you can access GET data using the =$_GET= superglobal array.

#+begin_src php
  <?php
  if (isset($_GET['name'])) {
      echo "Hello, " . htmlspecialchars($_GET['name']);
  }
  ?>
#+end_src

** POST Method
    :PROPERTIES:
    :CUSTOM_ID: post-method
    :END:

The POST method sends data through the HTTP request body. It's used for
sending data to a server to create/update a resource and is not visible
in the URL.

*** Characteristics of POST:
     :PROPERTIES:
     :CUSTOM_ID: characteristics-of-post
     :END:

- Data is not displayed in the URL.
- Suitable for sending sensitive or large amounts of data.
- No size limitations for the amount of data (within practical limits).
- Cannot be bookmarked or cached.
- Slightly slower for small amounts of data due to overhead.

*** Example Usage:
     :PROPERTIES:
     :CUSTOM_ID: example-usage-1
     :END:

#+begin_src html
  <!-- HTML Form using POST method -->
  <form action="process.php" method="post">
      Name: <input type="text" name="name">
      <input type="submit" value="Submit">
  </form>
#+end_src

In PHP, POST data is accessed using the =$_POST= superglobal array.

#+begin_src php
  <?php
  if ($_SERVER["REQUEST_METHOD"] == "POST") {
      echo "Hello, " . htmlspecialchars($_POST['name']);
  }
  ?>
#+end_src

*** Conclusion
    :PROPERTIES:
    :CUSTOM_ID: conclusion
    :END:

- Use *GET* for simple, non-secure data retrieval, especially when you
  want to be able to bookmark or share the URL.
- Use *POST* for submitting forms, especially when dealing with
  sensitive data or when the amount of data is considerable.

Both methods are integral to PHP web development, allowing for efficient
data transfer between client and server. Understanding when and how to
use each method is key to building robust and secure web applications.
