plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.5'
}

group = 'daw2a'
version = '1.0.0'

java {
    toolchain { languageVersion = JavaLanguageVersion.of(25) }
}

repositories { mavenCentral() }

configurations { mockitoAgent }

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:4.0.5')
    testImplementation platform('org.springframework.boot:spring-boot-dependencies:4.0.5')
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    runtimeOnly 'com.h2database:h2'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    mockitoAgent('org.mockito:mockito-core:5.20.0') { transitive = false }
}

tasks.withType(JavaCompile).configureEach { options.compilerArgs += '-parameters' }
tasks.named('test') {
    useJUnitPlatform()
    jvmArgs "-javaagent:${configurations.mockitoAgent.singleFile}"
}
